/**
 * Collection definitions for the Enova Ops file-system database.
 *
 * Each entry declares the fields the engine validates, the secondary indexes it
 * maintains, and which fields must be unique. `search` lists the fields the
 * global search and list filters scan. `audit: false` opts a high-churn
 * collection out of the append-only audit trail.
 */

import {
  ROLE_KEYS, CUSTOMER_STATUS, CUSTOMER_TIERS, VENDOR_STATUS, VENDOR_CATEGORIES,
  ITEM_TYPES, UOMS, LOT_STATUS, LOCATION_TYPES, TXN_TYPES, PO_STATUS, SO_STATUS,
  PRIORITIES, HEALTH, PROJECT_STAGES, PROJECT_TERMINAL, PROJECT_TYPES,
  WORK_ORDER_STAGES, WORK_ORDER_TERMINAL, TASK_STATUS, FORMULA_FORMATS,
  FORMULA_STATUS, QUOTE_STATUS, DOCUMENT_CATEGORIES, DOCUMENT_STATUS,
  DOCUMENT_OWNER_TYPES, LABEL_REVIEW_STATUS, SAMPLE_STATUS, SAMPLE_TYPES,
  RFQ_STATUS, RFQ_SOURCE, enumValues,
} from '../../shared/domain.js';

const str = (label, extra = {}) => ({ type: 'string', label, ...extra });
const num = (label, extra = {}) => ({ type: 'number', label, ...extra });
const bool = (label, def = false) => ({ type: 'boolean', label, default: def });
const arr = (label) => ({ type: 'array', label, default: [] });
const obj = (label) => ({ type: 'object', label, default: {} });
const date = (label) => ({ type: 'date', label, default: null });
const oneOf = (label, list, def) => ({ type: 'string', label, enum: enumValues(list), default: def });

const stageValues = [...enumValues(PROJECT_STAGES), ...enumValues(PROJECT_TERMINAL)];
const woStageValues = [...enumValues(WORK_ORDER_STAGES), ...enumValues(WORK_ORDER_TERMINAL)];

export const schema = {
  // ── people & access ──────────────────────────────────────────────────────
  users: {
    label: 'Users',
    fields: {
      email: str('Email', { required: true }),
      name: str('Full name', { required: true }),
      initials: str('Initials'),
      role: { type: 'string', label: 'Role', required: true, enum: ROLE_KEYS },
      title: str('Job title'),
      department: str('Department'),
      phone: str('Phone'),
      passwordHash: str('Password hash'),
      passwordSalt: str('Password salt'),
      mustChangePassword: bool('Must change password', true),
      active: bool('Active', true),
      accentColor: str('Accent colour'),
      lastLoginAt: date('Last login'),
      preferences: obj('Preferences'),
    },
    indexes: ['role', 'active'],
    unique: ['email'],
    search: ['name', 'email', 'title', 'department'],
    redact: ['passwordHash', 'passwordSalt'],
  },

  sessions: {
    label: 'Sessions',
    audit: false,
    fields: {
      userId: str('User', { required: true }),
      token: str('Token', { required: true }),
      expiresAt: date('Expires'),
      ip: str('IP'),
      userAgent: str('User agent'),
      lastSeenAt: date('Last seen'),
    },
    indexes: ['userId'],
    unique: ['token'],
  },

  // ── commercial ───────────────────────────────────────────────────────────
  customers: {
    label: 'Customers',
    fields: {
      code: str('Customer code', { required: true }),
      name: str('Company name', { required: true }),
      status: oneOf('Status', CUSTOMER_STATUS, 'prospect'),
      tier: oneOf('Tier', CUSTOMER_TIERS, 'standard'),
      industry: str('Industry'),
      website: str('Website'),
      ownerId: str('Account manager'),
      paymentTerms: str('Payment terms', { default: 'Net 30' }),
      creditLimit: num('Credit limit'),
      // Pricing defaults for this account: the margin new quotes start at, and a
      // labour-rate factor (1 = list rates) for accounts with negotiated labour.
      defaultMargin: num('Default margin'),
      laborRateFactor: num('Labour rate factor', { default: 1 }),
      billingAddress: obj('Billing address'),
      shippingAddress: obj('Shipping address'),
      contacts: arr('Contacts'),
      logoTint: str('Logo tint'),
      notes: str('Notes'),
      tags: arr('Tags'),
    },
    indexes: ['status', 'ownerId', 'tier', 'tags'],
    unique: ['code'],
    search: ['name', 'code', 'industry', 'notes'],
  },

  salesOrders: {
    label: 'Orders',
    fields: {
      orderNumber: str('Order number', { required: true }),
      customerId: str('Customer', { required: true }),
      status: oneOf('Status', SO_STATUS, 'draft'),
      priority: oneOf('Priority', PRIORITIES, 'normal'),
      customerPo: str('Customer PO'),
      quoteId: str('Quote'),
      projectId: str('Project'),
      ownerId: str('Owner'),
      lines: arr('Lines'),
      subtotal: num('Subtotal'),
      freight: num('Freight'),
      total: num('Total'),
      requestedShipDate: date('Requested ship date'),
      promisedShipDate: date('Promised ship date'),
      shippedAt: date('Shipped'),
      notes: str('Notes'),
      tags: arr('Tags'),
    },
    indexes: ['customerId', 'status', 'ownerId', 'projectId'],
    unique: ['orderNumber'],
    search: ['orderNumber', 'customerPo', 'notes'],
  },

  shipments: {
    label: 'Shipments',
    fields: {
      shipmentNumber: str('Shipment number', { required: true }),
      salesOrderId: str('Order'),
      customerId: str('Customer'),
      status: { type: 'string', label: 'Status', enum: ['packing', 'ready', 'in_transit', 'delivered', 'exception'], default: 'packing' },
      carrier: str('Carrier'),
      service: str('Service level'),
      trackingNumber: str('Tracking number'),
      cartons: num('Cartons'),
      weightLb: num('Weight (lb)'),
      cost: num('Freight cost'),
      lines: arr('Lines'),
      shippedAt: date('Shipped'),
      deliveredAt: date('Delivered'),
      notes: str('Notes'),
    },
    indexes: ['salesOrderId', 'customerId', 'status'],
    unique: ['shipmentNumber'],
    search: ['shipmentNumber', 'trackingNumber', 'carrier'],
  },

  // ── documents ────────────────────────────────────────────────────────────
  documents: {
    label: 'Documents',
    fields: {
      name: str('Document name', { required: true }),
      category: oneOf('Category', DOCUMENT_CATEGORIES, 'other'),
      status: oneOf('Status', DOCUMENT_STATUS, 'draft'),
      ownerType: { type: 'string', label: 'Attached to', enum: DOCUMENT_OWNER_TYPES, default: 'general' },
      ownerId: str('Owner record'),
      customerId: str('Customer'),
      vendorId: str('Vendor'),
      currentVersion: num('Current version', { default: 1 }),
      versions: arr('Versions'),
      effectiveDate: date('Effective'),
      expiresAt: date('Expires'),
      reviewerId: str('Reviewer'),
      approvedBy: str('Approved by'),
      approvedAt: date('Approved'),
      confidential: bool('Confidential'),
      description: str('Description'),
      tags: arr('Tags'),
    },
    indexes: ['ownerType', 'ownerId', 'customerId', 'vendorId', 'category', 'status', 'tags'],
    search: ['name', 'description', 'tags'],
  },

  // ── supply ───────────────────────────────────────────────────────────────
  vendors: {
    label: 'Vendors',
    fields: {
      code: str('Vendor code', { required: true }),
      name: str('Vendor name', { required: true }),
      status: oneOf('Status', VENDOR_STATUS, 'pending'),
      category: oneOf('Category', VENDOR_CATEGORIES, 'raw_material'),
      contacts: arr('Contacts'),
      address: obj('Address'),
      website: str('Website'),
      leadTimeDays: num('Lead time (days)', { default: 21 }),
      paymentTerms: str('Payment terms', { default: 'Net 30' }),
      minimumOrder: num('Minimum order'),
      qualification: obj('Qualification'),
      rating: obj('Scorecard'),
      buyerId: str('Buyer'),
      notes: str('Notes'),
      tags: arr('Tags'),
    },
    indexes: ['status', 'category', 'buyerId', 'tags'],
    unique: ['code'],
    search: ['name', 'code', 'notes', 'tags'],
  },

  purchaseOrders: {
    label: 'Purchase orders',
    fields: {
      poNumber: str('PO number', { required: true }),
      vendorId: str('Vendor', { required: true }),
      status: oneOf('Status', PO_STATUS, 'draft'),
      buyerId: str('Buyer'),
      lines: arr('Lines'),
      subtotal: num('Subtotal'),
      freight: num('Freight'),
      tax: num('Tax'),
      total: num('Total'),
      currency: str('Currency', { default: 'USD' }),
      orderedAt: date('Ordered'),
      expectedAt: date('Expected'),
      receivedAt: date('Received'),
      approvedBy: str('Approved by'),
      approvedAt: date('Approved'),
      terms: str('Terms'),
      shipTo: str('Ship to'),
      notes: str('Notes'),
    },
    indexes: ['vendorId', 'status', 'buyerId'],
    unique: ['poNumber'],
    search: ['poNumber', 'notes'],
  },

  // ── inventory ────────────────────────────────────────────────────────────
  items: {
    label: 'Items',
    fields: {
      itemCode: str('Item code', { required: true }),
      name: str('Item name', { required: true }),
      type: oneOf('Type', ITEM_TYPES, 'raw_material'),
      category: str('Category'),
      form: str('Form / grade'),
      uom: { type: 'string', label: 'Unit of measure', enum: UOMS, default: 'kg' },
      costPerUom: num('Cost per UOM'),
      pricePerKg: num('Price per kg'),
      priceSource: str('Price source', { default: 'Enova price list' }),
      reorderPoint: num('Reorder point'),
      reorderQty: num('Reorder quantity'),
      safetyStock: num('Safety stock'),
      leadTimeDays: num('Lead time (days)', { default: 21 }),
      defaultVendorId: str('Preferred vendor'),
      defaultLocationId: str('Default location'),
      shelfLifeDays: num('Shelf life (days)', { default: 730 }),
      storageConditions: str('Storage conditions'),
      allergens: arr('Allergens'),
      isBranded: bool('Branded ingredient'),
      brandOwner: str('Trademark owner'),
      labelName: str('Label declaration name'),
      requiresCoa: bool('Requires COA', true),
      // Set when this item is something Enova makes rather than buys — a finished
      // good or an intermediate blend. Planning then raises batches for it, not
      // purchase orders, and explodes those batches into their own ingredients.
      madeByFormulaId: str('Made by formula'),
      active: bool('Active', true),
      notes: str('Notes'),
      tags: arr('Tags'),
    },
    indexes: ['type', 'category', 'defaultVendorId', 'active', 'tags'],
    unique: ['itemCode'],
    search: ['name', 'itemCode', 'category', 'form', 'brandOwner', 'tags'],
  },

  locations: {
    label: 'Locations',
    fields: {
      code: str('Location code', { required: true }),
      name: str('Name', { required: true }),
      type: oneOf('Type', LOCATION_TYPES, 'rack'),
      parentId: str('Parent location'),
      temperatureControlled: bool('Temperature controlled'),
      capacity: num('Capacity'),
      active: bool('Active', true),
      notes: str('Notes'),
    },
    indexes: ['type', 'parentId', 'active'],
    unique: ['code'],
    search: ['code', 'name'],
  },

  lots: {
    label: 'Lots',
    fields: {
      lotNumber: str('Lot number', { required: true }),
      itemId: str('Item', { required: true }),
      vendorId: str('Vendor'),
      vendorLot: str('Vendor lot'),
      purchaseOrderId: str('Purchase order'),
      workOrderId: str('Work order'),
      status: oneOf('Status', LOT_STATUS, 'quarantine'),
      qtyReceived: num('Quantity received'),
      qtyOnHand: num('Quantity on hand'),
      uom: { type: 'string', label: 'UOM', enum: UOMS, default: 'kg' },
      locationId: str('Location'),
      unitCost: num('Unit cost'),
      receivedAt: date('Received'),
      manufacturedAt: date('Manufactured'),
      expiresAt: date('Expires'),
      retestAt: date('Retest due'),
      coaDocumentId: str('COA document'),
      coaReceived: bool('COA on file'),
      testResults: arr('Test results'),
      dispositionBy: str('Disposition by'),
      dispositionAt: date('Disposition date'),
      notes: str('Notes'),
    },
    indexes: ['itemId', 'status', 'locationId', 'vendorId', 'purchaseOrderId'],
    unique: ['lotNumber'],
    search: ['lotNumber', 'vendorLot', 'notes'],
  },

  inventoryTxns: {
    label: 'Inventory transactions',
    fields: {
      txnNumber: str('Transaction number'),
      type: oneOf('Type', TXN_TYPES, 'adjustment'),
      itemId: str('Item', { required: true }),
      lotId: str('Lot'),
      qty: num('Quantity', { required: true }),
      uom: { type: 'string', label: 'UOM', enum: UOMS, default: 'kg' },
      fromLocationId: str('From location'),
      toLocationId: str('To location'),
      refType: str('Reference type'),
      refId: str('Reference'),
      reason: str('Reason'),
      unitCost: num('Unit cost'),
      balanceAfter: num('Balance after'),
      performedAt: date('Performed at'),
    },
    indexes: ['itemId', 'lotId', 'type', 'refId'],
    search: ['txnNumber', 'reason'],
  },

  cycleCounts: {
    label: 'Cycle counts',
    fields: {
      countNumber: str('Count number', { required: true }),
      locationId: str('Location'),
      // What the sheet covers: one location, a set of items, or everything on hand.
      scope: { type: 'string', label: 'Scope', enum: ['location', 'items', 'all'], default: 'location' },
      itemIds: arr('Items in scope'),
      // Blind: counters do not see the book quantity until the sheet is in review.
      blind: bool('Blind count'),
      tolerancePct: num('Tolerance %', { default: 2 }),
      status: { type: 'string', label: 'Status', enum: ['scheduled', 'counting', 'review', 'closed', 'cancelled'], default: 'scheduled' },
      scheduledFor: date('Scheduled for'),
      // [{ lotId, lotNumber, itemId, uom, unitCost, expectedQty, countedQty, variance, countedBy, countedAt, recount, note }]
      lines: arr('Lines'),
      countedBy: str('Counted by'),
      startedAt: date('Counting started'),
      reviewedAt: date('Sent to review'),
      closedBy: str('Closed by'),
      closedAt: date('Closed'),
      postedValue: num('Net adjustment value'),
      postedLines: num('Lines adjusted'),
      notes: str('Notes'),
    },
    indexes: ['status', 'locationId'],
    unique: ['countNumber'],
    search: ['countNumber', 'notes'],
  },

  // ── development ──────────────────────────────────────────────────────────
  projects: {
    label: 'Projects',
    fields: {
      code: str('Project code', { required: true }),
      name: str('Project name', { required: true }),
      customerId: str('Customer'),
      stage: { type: 'string', label: 'Stage', enum: stageValues, default: 'intake' },
      type: oneOf('Type', PROJECT_TYPES, 'new_product'),
      priority: oneOf('Priority', PRIORITIES, 'normal'),
      health: oneOf('Health', HEALTH, 'on_track'),
      ownerId: str('Owner'),
      teamIds: arr('Team'),
      formulaId: str('Formula'),
      quoteId: str('Quote'),
      format: str('Format'),
      // Product change control — the project is the production-of-record for its
      // formula, label, packaging and price.
      lockState: { type: 'string', label: 'Lock state', enum: ['open', 'pending_approval', 'locked'], default: 'open' },
      productRevision: num('Revision', { default: 1 }),
      approval: obj('Current approval'),
      approvalHistory: arr('Approval history'),
      approvalToken: str('Approval link token'),
      approvalRequestedAt: date('Approval requested'),
      targetLaunch: date('Target launch'),
      brief: str('Brief'),
      requirements: arr('Requirements'),
      milestones: arr('Milestones'),
      gateChecks: arr('Gate checks'),
      risks: arr('Risks'),
      progress: num('Progress %'),
      boardOrder: num('Board order', { default: 1000 }),
      stageEnteredAt: date('Stage entered'),
      tags: arr('Tags'),
      notes: str('Notes'),
    },
    indexes: ['stage', 'customerId', 'ownerId', 'health', 'teamIds', 'tags'],
    unique: ['code'],
    search: ['name', 'code', 'brief', 'tags'],
  },

  formulas: {
    label: 'Formulas',
    fields: {
      code: str('Formula code', { required: true }),
      name: str('Formula name', { required: true }),
      revision: num('Revision', { default: 1 }),
      status: oneOf('Status', FORMULA_STATUS, 'draft'),
      supersedesId: str('Supersedes'),
      customerId: str('Customer'),
      projectId: str('Project'),
      format: { type: 'string', label: 'Format', enum: enumValues(FORMULA_FORMATS), default: 'capsule' },
      isBulk: bool('Bulk (unpackaged)'),
      servingSize: str('Serving size', { default: '1 capsule' }),
      servingsPerUnit: num('Servings per unit', { default: 30 }),
      unitsPerBatch: num('Units per batch', { default: 10000 }),
      totalFormatWeightMg: num('Total format weight (mg)', { default: 600 }),
      capsuleShellSize: str('Capsule shell size'),
      overagePct: num('Overage %', { default: 5 }),
      // How the batch runs: a routing of operations with setup and run rates.
      // Empty means "the default routing for this format".
      routingId: str('Routing'),
      actives: arr('Active ingredients'),
      excipients: arr('Excipients'),
      // The stockable item this formula makes — a finished good, or an
      // intermediate (a blend) that another formula consumes. Kept in sync with
      // items.madeByFormulaId so a bill of materials can go more than one level.
      producesItemId: str('Produces item'),
      packaging: arr('Packaging'),
      services: arr('Manufacturing services'),
      allergens: arr('Allergens'),
      claims: arr('Label claims'),
      ownerId: str('Owner'),
      approvedBy: str('Approved by'),
      approvedAt: date('Approved'),
      notes: str('Notes'),
      tags: arr('Tags'),
    },
    indexes: ['status', 'customerId', 'projectId', 'format', 'tags'],
    unique: ['code'],
    search: ['name', 'code', 'notes', 'tags'],
  },

  quotes: {
    label: 'Quotes',
    fields: {
      quoteNumber: str('Quote number', { required: true }),
      title: str('Title', { required: true }),
      customerId: str('Customer'),
      formulaId: str('Formula'),
      projectId: str('Project'),
      status: oneOf('Status', QUOTE_STATUS, 'draft'),
      revision: num('Revision', { default: 1 }),
      ownerId: str('Owner'),
      coaFee: num('COA fee', { default: 120 }),
      tiers: arr('Quantity tiers'),
      snapshot: obj('Formula snapshot'),
      result: obj('Computed result'),
      leadTimeWeeks: num('Lead time (weeks)', { default: 8 }),
      paymentTerms: str('Payment terms'),
      validUntil: date('Valid until'),
      sentAt: date('Sent'),
      decidedAt: date('Decided'),
      notes: str('Notes'),
      tags: arr('Tags'),
    },
    indexes: ['customerId', 'formulaId', 'status', 'ownerId'],
    unique: ['quoteNumber'],
    search: ['quoteNumber', 'title', 'notes'],
  },

  // ── production ───────────────────────────────────────────────────────────
  // Canned jobs: a customer's repeat purchase — product, quantity and the
  // agreed price — ready to become an order (and a batch) in one click.
  orderTemplates: {
    label: 'Repeat orders',
    fields: {
      name: str('Name', { required: true }),
      customerId: str('Customer', { required: true }),
      projectId: str('Project'),
      formulaId: str('Formula'),
      quoteId: str('Quote'),
      qty: num('Quantity'),
      unitPrice: num('Unit price'),
      bulk: bool('Bulk'),
      leadTimeWeeks: num('Lead time (weeks)'),
      notes: str('Notes'),
      timesUsed: num('Times used'),
      lastUsedAt: date('Last used'),
      active: bool('Active', { default: true }),
      tags: arr('Tags'),
    },
    indexes: ['customerId', 'projectId', 'formulaId'],
    search: ['name', 'notes'],
  },

  routings: {
    label: 'Routings',
    fields: {
      code: str('Routing code', { required: true }),
      name: str('Routing name', { required: true }),
      format: { type: 'string', label: 'Format', enum: enumValues(FORMULA_FORMATS), default: 'capsule' },
      isDefault: bool('Default for its format'),
      hoursPerShift: num('Hours per shift', { default: 8 }),
      // [{ seq, name, workCenter, setupMin, runRatePerHour, runMin, crew, laborRate, requiresSignature }]
      operations: arr('Operations'),
      notes: str('Notes'),
      tags: arr('Tags'),
    },
    indexes: ['format', 'isDefault'],
    unique: ['code'],
    search: ['name', 'code', 'notes'],
  },

  workOrders: {
    label: 'Work orders',
    fields: {
      woNumber: str('Work order', { required: true }),
      batchNumber: str('Batch number'),
      stage: { type: 'string', label: 'Stage', enum: woStageValues, default: 'planned' },
      priority: oneOf('Priority', PRIORITIES, 'normal'),
      productName: str('Product', { required: true }),
      formulaId: str('Formula'),
      projectId: str('Project'),
      customerId: str('Customer'),
      salesOrderId: str('Sales order'),
      line: str('Production line'),
      plannedQty: num('Planned quantity'),
      actualQty: num('Actual quantity'),
      uom: { type: 'string', label: 'UOM', enum: UOMS, default: 'ea' },
      plannedStart: date('Planned start'),
      plannedEnd: date('Planned end'),
      actualStart: date('Actual start'),
      actualEnd: date('Actual end'),
      supervisorId: str('Supervisor'),
      operatorIds: arr('Operators'),
      materials: arr('Materials'),
      steps: arr('Batch steps'),
      qcChecks: arr('QC checks'),
      deviations: arr('Deviations'),
      yieldPct: num('Yield %'),
      holdReason: str('Hold reason'),
      boardOrder: num('Board order', { default: 1000 }),
      stageEnteredAt: date('Stage entered'),
      releasedBy: str('Released by'),
      releasedAt: date('Released'),
      // What the batch actually made: the finished-goods lot it produced and the
      // real material cost behind it (from the lots that were issued).
      outputLotId: str('Output lot'),
      actualMaterialCost: num('Actual material cost'),
      actualUnitCost: num('Actual cost per unit'),
      // The standard, frozen when the batch was planned, so variance is measured
      // against what we expected then — not against today's price list.
      standardUnitCost: num('Standard material cost per unit'),
      standardMaterialCost: num('Standard material cost'),
      // Labor: standard from the routing at planning, actual from the time the
      // floor clocks against each step.
      routingId: str('Routing'),
      standardLaborMin: num('Standard labor (min)'),
      standardLaborCost: num('Standard labor cost'),
      actualLaborMin: num('Actual labor (min)'),
      actualLaborCost: num('Actual labor cost'),
      notes: str('Notes'),
      tags: arr('Tags'),
    },
    indexes: ['stage', 'customerId', 'formulaId', 'projectId', 'supervisorId', 'salesOrderId', 'line'],
    unique: ['woNumber'],
    search: ['woNumber', 'batchNumber', 'productName', 'notes'],
  },

  // ── label review ─────────────────────────────────────────────────────────
  labelReviews: {
    label: 'Label reviews',
    fields: {
      reviewNumber: str('Review number', { required: true }),
      productName: str('Product name', { required: true }),
      brand: str('Brand'),
      customerId: str('Customer'),
      projectId: str('Project'),
      formulaId: str('Formula'),
      status: oneOf('Status', LABEL_REVIEW_STATUS, 'draft'),
      labelRevision: str('Label revision'),
      source: { type: 'string', label: 'Source', enum: ['text', 'pdf', 'image', 'artwork'], default: 'text' },
      receivedAt: date('Received'),
      panels: obj('Panel copy'),
      checklist: arr('Checklist rows'),
      findings: arr('Findings'),
      supplementFacts: obj('Supplement Facts panel'),
      metrics: obj('Completion metrics'),
      reviewerId: str('Reviewer'),
      reviewedAt: date('Reviewed'),
      approverId: str('Approver'),
      approvedAt: date('Approved'),
      documentIds: arr('Linked documents'),
      notes: str('Notes'),
      tags: arr('Tags'),
    },
    indexes: ['status', 'customerId', 'projectId', 'reviewerId'],
    unique: ['reviewNumber'],
    search: ['reviewNumber', 'productName', 'brand', 'notes'],
  },

  // ── samples ──────────────────────────────────────────────────────────────
  samples: {
    label: 'Samples',
    fields: {
      sampleNumber: str('Sample number', { required: true }),
      type: oneOf('Type', SAMPLE_TYPES, 'customer'),
      status: oneOf('Status', SAMPLE_STATUS, 'requested'),
      productName: str('Product', { required: true }),
      projectId: str('Project'),
      customerId: str('Customer'),
      formulaId: str('Formula'),
      lotId: str('Lot'),
      lotNumber: str('Lot number'),
      quantity: num('Quantity'),
      uom: { type: 'string', label: 'UOM', enum: UOMS, default: 'ea' },
      recipientName: str('Recipient'),
      recipientCompany: str('Recipient company'),
      shipTo: str('Ship to'),
      carrier: str('Carrier'),
      trackingNumber: str('Tracking number'),
      requestedById: str('Requested by'),
      ownerId: str('Owner'),
      requestedAt: date('Requested'),
      shippedAt: date('Shipped'),
      deliveredAt: date('Delivered'),
      dueBy: date('Feedback due'),
      respondedAt: date('Responded'),
      outcome: { type: 'string', label: 'Outcome', enum: ['', 'approved', 'changes', 'rejected'], default: '' },
      feedback: str('Feedback'),
      boardOrder: num('Board order', { default: 1000 }),
      stageEnteredAt: date('Stage entered'),
      notes: str('Notes'),
      tags: arr('Tags'),
    },
    indexes: ['status', 'type', 'customerId', 'projectId', 'formulaId', 'ownerId'],
    unique: ['sampleNumber'],
    search: ['sampleNumber', 'productName', 'recipientName', 'recipientCompany', 'trackingNumber', 'notes'],
  },

  // ── quote requests (RFQ intake) ───────────────────────────────────────────
  rfqs: {
    label: 'Quote requests',
    fields: {
      rfqNumber: str('Request number', { required: true }),
      status: oneOf('Status', RFQ_STATUS, 'new'),
      productName: str('Product', { required: true }),
      customerId: str('Customer'),
      customerName: str('Company'),
      contactName: str('Contact'),
      contactEmail: str('Contact email'),
      source: oneOf('Source', RFQ_SOURCE, 'email'),
      format: str('Format'),
      servingSize: str('Serving size'),
      desiredActives: str('Desired ingredients'),
      targetQty: num('Target quantity'),
      targetPrice: num('Target price / unit'),
      priority: oneOf('Priority', PRIORITIES, 'normal'),
      dueDate: date('Quote needed by'),
      ownerId: str('Owner'),
      projectId: str('Project'),
      formulaId: str('Formula'),
      quoteId: str('Quote'),
      outcome: { type: 'string', label: 'Outcome', enum: ['', 'won', 'lost'], default: '' },
      lostReason: str('Reason lost'),
      boardOrder: num('Board order', { default: 1000 }),
      stageEnteredAt: date('Stage entered'),
      notes: str('Notes'),
      tags: arr('Tags'),
    },
    indexes: ['status', 'customerId', 'ownerId', 'priority'],
    unique: ['rfqNumber'],
    search: ['rfqNumber', 'productName', 'customerName', 'contactName', 'desiredActives', 'notes'],
  },

  // ── coordination ─────────────────────────────────────────────────────────
  tasks: {
    label: 'Tasks',
    fields: {
      title: str('Title', { required: true }),
      description: str('Description'),
      status: oneOf('Status', TASK_STATUS, 'todo'),
      priority: oneOf('Priority', PRIORITIES, 'normal'),
      assigneeId: str('Assignee'),
      dueDate: date('Due date'),
      refType: str('Linked to'),
      refId: str('Linked record'),
      refLabel: str('Link label'),
      boardOrder: num('Board order', { default: 1000 }),
      completedAt: date('Completed'),
      tags: arr('Tags'),
    },
    indexes: ['status', 'assigneeId', 'refId', 'tags'],
    search: ['title', 'description'],
  },

  comments: {
    label: 'Comments',
    fields: {
      refType: str('Record type', { required: true }),
      refId: str('Record', { required: true }),
      body: str('Comment', { required: true }),
      authorId: str('Author'),
      mentions: arr('Mentions'),
      pinned: bool('Pinned'),
    },
    indexes: ['refId', 'authorId'],
    search: ['body'],
  },

  activity: {
    label: 'Activity',
    audit: false,
    fields: {
      type: str('Type', { required: true }),
      title: str('Title', { required: true }),
      detail: str('Detail'),
      actorId: str('Actor'),
      actorName: str('Actor name'),
      refType: str('Record type'),
      refId: str('Record'),
      link: str('Link'),
      tone: str('Tone', { default: 'neutral' }),
    },
    indexes: ['type', 'actorId', 'refId'],
    search: ['title', 'detail'],
  },

  notifications: {
    label: 'Notifications',
    audit: false,
    fields: {
      userId: str('User', { required: true }),
      title: str('Title', { required: true }),
      body: str('Body'),
      link: str('Link'),
      severity: { type: 'string', label: 'Severity', enum: ['info', 'success', 'warning', 'danger'], default: 'info' },
      read: bool('Read'),
      readAt: date('Read at'),
    },
    indexes: ['userId', 'read'],
    search: ['title', 'body'],
  },

  settings: {
    label: 'Settings',
    fields: {
      key: str('Key', { required: true }),
      value: { type: 'any', label: 'Value' },
      label: str('Label'),
      category: str('Category', { default: 'general' }),
      description: str('Description'),
    },
    indexes: ['category'],
    unique: ['key'],
    search: ['key', 'label', 'description'],
  },

  savedViews: {
    label: 'Saved views',
    fields: {
      name: str('Name', { required: true }),
      module: str('Module', { required: true }),
      ownerId: str('Owner'),
      shared: bool('Shared with team'),
      config: obj('View configuration'),
      icon: str('Icon'),
      boardOrder: num('Order', { default: 1000 }),
    },
    indexes: ['module', 'ownerId', 'shared'],
    search: ['name'],
  },
};

/** Collections a non-admin may read and write through the generic CRUD API. */
export const COLLECTION_PERMISSIONS = {
  customers: { read: null, write: 'customers.write' },
  salesOrders: { read: null, write: 'orders.write' },
  shipments: { read: null, write: 'orders.write' },
  documents: { read: null, write: 'documents.write' },
  vendors: { read: null, write: 'vendors.write' },
  purchaseOrders: { read: null, write: 'po.write' },
  items: { read: null, write: 'inventory.write' },
  locations: { read: null, write: 'inventory.write' },
  lots: { read: null, write: 'inventory.write' },
  inventoryTxns: { read: null, write: 'inventory.write' },
  cycleCounts: { read: null, write: 'inventory.write' },
  projects: { read: null, write: 'projects.write' },
  formulas: { read: null, write: 'formulas.write' },
  quotes: { read: 'cost.view', write: 'quotes.write' },
  orderTemplates: { read: null, write: 'orders.write' },
  routings: { read: null, write: 'production.write' },
  workOrders: { read: null, write: 'production.write' },
  labelReviews: { read: null, write: 'labels.write' },
  samples: { read: null, write: 'samples.write' },
  rfqs: { read: null, write: 'quotes.write' },
  tasks: { read: null, write: 'tasks.write' },
  comments: { read: null, write: 'tasks.write' },
  activity: { read: null, write: null },
  notifications: { read: null, write: 'tasks.write' },
  settings: { read: null, write: 'settings.manage' },
  savedViews: { read: null, write: 'tasks.write' },
  users: { read: null, write: 'users.manage' },
  sessions: { read: 'users.manage', write: 'users.manage' },
};

/** Strip fields that must never leave the server. */
export function redact(collection, record) {
  const fields = schema[collection]?.redact;
  if (!fields || !record) return record;
  const copy = { ...record };
  for (const field of fields) delete copy[field];
  return copy;
}

export const searchableFields = (collection) => schema[collection]?.search ?? ['name'];
